name: CR

on:
  pull_request_target:
    types: [labeled, unlabeled]

jobs:
  publish-pr:
    if: ${{ !github.event.pull_request.draft && contains(github.event.pull_request.labels.*.name, 'publish-pr') && !contains(github.event.pull_request.labels.*.name, 'spam') && !contains(github.event.pull_request.labels.*.name, 'invalid') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: pnpm install
      - run: pnpm build
      - run: npx pkg-pr-new publish --compact --no-template --pnpm
